version: '2'

services:
  deliveryserviceDb:
    image: mysql
    container_name: deliveryserviceDb
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deliveryserviceDb
