server:
  port: 8087

spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:3306/0_orderservice
#    username: root
#    password:
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: configserver:http://localhost:9296

