server:
  port: 8087

spring:
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: configserver:http://localhost:9296
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notificationId
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    topic:
      name: order
  mail:
    host: smtp.gmail.com
    port: 587
    username: phamdacdy@gmail.com
    password: xtycolcbhgjodvym
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
