server:
  port: 9091

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE-PUBLIC
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/public/api/v1/product/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: '*'
              maxAge: 30
        - id: PRODUCT-SERVICE-PRIVATE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/private/api/v1/product/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: '*'
              maxAge: 30
        - id: CART-SERVICE-PRIVATE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/private/api/v1/cart/**
        - id: ORDER-SERVICE-PUBLIC
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/public/api/v1/order/**
        - id: ORDER-SERVICE-PRIVATE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/private/api/v1/order/**
        - id: PAYMENT-SERVICE-PUBLIC
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/public/api/v1/payment/**
        - id: DELIVERY-SERVICE-PUBLIC
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/public/api/v1/delivery/**
        - id: DELIVERY-SERVICE-PRIVATE
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/private/api/v1/delivery/**
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/public/api/v1/notification/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/oauthrealm"
          jwk-set-uri: "http://localhost:9090/realms/oauthrealm/protocol/openid-connect/certs"

jwt:
  auth:
    converter:
      resource-id: microservice_ecommerce
      principle-attribute: preferred_username
